"""followers table

Revision ID: 4472edf3c333
Revises: 9fc4904e4048
Create Date: 2020-12-04 09:57:12.749199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4472edf3c333'
down_revision = '9fc4904e4048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'id')
    # ### end Alembic commands ###
