"""followers

Revision ID: 9fc4904e4048
Revises: d7a93495db01
Create Date: 2020-12-04 08:56:25.441501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc4904e4048'
down_revision = 'd7a93495db01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followerId', sa.Integer(), nullable=True))
    op.add_column('followers', sa.Column('followingId', sa.Integer(), nullable=True))
    op.create_unique_constraint('uniqueIdx', 'followers', ['followerId', 'followingId'])
    op.drop_constraint('followers_followingUserId_fkey', 'followers', type_='foreignkey')
    op.drop_constraint('followers_userId_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'users', ['followingId'], ['id'])
    op.create_foreign_key(None, 'followers', 'users', ['followerId'], ['id'])
    op.drop_column('followers', 'userId')
    op.drop_column('followers', 'followingUserId')
    op.drop_column('followers', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('followers', sa.Column('followingUserId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('followers', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_userId_fkey', 'followers', 'users', ['userId'], ['id'])
    op.create_foreign_key('followers_followingUserId_fkey', 'followers', 'users', ['followingUserId'], ['id'])
    op.drop_constraint('uniqueIdx', 'followers', type_='unique')
    op.drop_column('followers', 'followingId')
    op.drop_column('followers', 'followerId')
    # ### end Alembic commands ###
